// [quote, author]. Add, edit or delete lines freely; any language works.
// Every quote here comes from a book (no films, speeches or unsourced sayings).
// The groups are mixed together so the quote of the day does not stay on one source for long.
const tolkien = [
  ["All we have to decide is what to do with the time that is given us.", "Gandalf, The Fellowship of the Ring"],
  ["Not all those who wander are lost.", "J.R.R. Tolkien, The Fellowship of the Ring"],
  ["It's the job that's never started as takes longest to finish.", "Sam Gamgee, The Lord of the Rings"],
  ["Despair is only for those who see the end beyond all doubt. We do not.", "Gandalf, The Fellowship of the Ring"],
  ["If more of us valued food and cheer and song above hoarded gold, it would be a merrier world.", "Thorin, The Hobbit"],
  ["The world is indeed full of peril, and in it there are many dark places; but still there is much that is fair.", "Haldir, The Fellowship of the Ring"],
  ["I will not say: do not weep; for not all tears are an evil.", "Gandalf, The Return of the King"],
  ["Faithless is he that says farewell when the road darkens.", "Gimli, The Fellowship of the Ring"],
  ["Yet the deeds will not be less valiant because they are unpraised.", "J.R.R. Tolkien, The Lord of the Rings"],
  ["Let him not vow to walk in the dark, who has not seen the nightfall.", "Elrond, The Fellowship of the Ring"],
  ["He that breaks a thing to find out what it is, has left the path of wisdom.", "Gandalf, The Fellowship of the Ring"],
  ["The wide world is all about you: you can fence yourselves in, but you cannot forever fence it out.", "Gildor, The Fellowship of the Ring"],
  ["In this hour, I do not believe that any darkness will endure.", "Faramir, The Return of the King"],
  ["Who knows? Have patience. Go where you must go, and hope!", "Gandalf, The Fellowship of the Ring"],
  ["You can trust us to stick to you through thick and thin, to the bitter end.", "Merry, The Fellowship of the Ring"],
  ["I will take the Ring, though I do not know the way.", "Frodo, The Fellowship of the Ring"],
  ["Yet such is oft the course of deeds that move the wheels of the world: small hands do them because they must, while the eyes of the great are elsewhere.", "Elrond, The Fellowship of the Ring"],
  ["Don't adventures ever have an end? I suppose not. Someone else always has to carry on the story.", "Bilbo, The Fellowship of the Ring"],
  ["You step into the Road, and if you don't keep your feet, there is no knowing where you might be swept off to.", "Bilbo, The Fellowship of the Ring"],
  ["I don't know half of you half as well as I should like, and I like less than half of you half as well as you deserve.", "Bilbo, The Fellowship of the Ring"],
  ["Speak, friend, and enter.", "The Doors of Durin, The Fellowship of the Ring"],
  ["I am looking for someone to share in an adventure that I am arranging, and it's very difficult to find anyone.", "Gandalf, The Hobbit"],
  ["It does not do to leave a live dragon out of your calculations, if you live near him.", "Gandalf, The Hobbit"],
  ["Never laugh at live dragons, Bilbo you fool!", "Bilbo, The Hobbit"],
];
const narnia = [
  ["Courage, dear heart.", "Aslan, The Voyage of the Dawn Treader"],
  ["He's not a tame lion. But he is good.", "Mr. Beaver, The Lion, the Witch and the Wardrobe"],
  ["Always winter but never Christmas.", "The Lion, the Witch and the Wardrobe"],
  ["Once a King or Queen of Narnia, always a King or Queen of Narnia.", "Aslan, The Lion, the Witch and the Wardrobe"],
  ["Safe? Who said anything about safe? 'Course he isn't safe. But he's good. He's the King, I tell you.", "Mr. Beaver, The Lion, the Witch and the Wardrobe"],
  ["One day you will be old enough to start reading fairy tales again.", "C.S. Lewis, dedication of The Lion, the Witch and the Wardrobe"],
  ["If you are thirsty, come and drink.", "Aslan, The Silver Chair"],
  ["You would not have called to me unless I had been calling to you.", "Aslan, The Silver Chair"],
  ["I'm on Aslan's side even if there isn't any Aslan to lead it. I'm going to live as like a Narnian as I can even if there isn't any Narnia.", "Puddleglum, The Silver Chair"],
  ["Further up and further in!", "The Last Battle"],
  ["What you see and what you hear depends a great deal on where you are standing. It also depends on what sort of person you are.", "C.S. Lewis, The Magician's Nephew"],
  ["Every year you grow, you will find me bigger.", "Aslan, Prince Caspian"],
  ["Things never happen the same way twice.", "Aslan, Prince Caspian"],
  ["Even in your world, my son, that is not what a star is, but only what it is made of.", "Ramandu, The Voyage of the Dawn Treader"],
  ["People who have not been in Narnia sometimes think that a thing cannot be good and terrible at the same time.", "C.S. Lewis, The Lion, the Witch and the Wardrobe"],
  ["Friendship is unnecessary, like philosophy, like art... It has no survival value; rather it is one of those things that give value to survival.", "C.S. Lewis, The Four Loves"],
  ["All find what they truly seek.", "The Last Battle"],
  ["There was a boy called Eustace Clarence Scrubb, and he almost deserved it.", "C.S. Lewis, The Voyage of the Dawn Treader"],
];
const lit = [
  ["Above all, don't lie to yourself. The man who lies to himself and listens to his own lie comes to a point that he cannot distinguish the truth within him, or around him, and so loses all respect for himself and for others.", "Fyodor Dostoevsky, The Brothers Karamazov"],
  ["You never really understand a person until you consider things from his point of view... Until you climb inside of his skin and walk around in it.", "Harper Lee, To Kill a Mockingbird"],
  ["I am no bird; and no net ensnares me: I am a free human being with an independent will.", "Charlotte Brontë, Jane Eyre"],
  ["Life appears to me too short to be spent in nursing animosity or registering wrongs.", "Charlotte Brontë, Jane Eyre"],
  ["The strongest of all warriors are these two: Time and Patience.", "Leo Tolstoy, War and Peace"],
  ["To go wrong in one's own way is better than to go right in someone else's.", "Fyodor Dostoevsky, Crime and Punishment"],
  ["And now that you don't have to be perfect, you can be good.", "John Steinbeck, East of Eden"],
  ["Whenever you feel like criticizing anyone, just remember that all the people in this world haven't had the advantages that you've had.", "F. Scott Fitzgerald, The Great Gatsby"],
  ["So we beat on, boats against the current, borne back ceaselessly into the past.", "F. Scott Fitzgerald, The Great Gatsby"],
  ["We need never be ashamed of our tears.", "Charles Dickens, Great Expectations"],
  ["Words can be like X-rays if you use them properly.", "Aldous Huxley, Brave New World"],
  ["It isn't what we say or think that defines us, but what we do.", "Jane Austen, Sense and Sensibility"],
  ["Do nothing which is of no use.", "Miyamoto Musashi, The Book of Five Rings"],
  ["Despite everything, I believe that people are really good at heart.", "Anne Frank, The Diary of a Young Girl"],
  ["It doesn't matter who you are or what you look like, so long as somebody loves you.", "Roald Dahl, The Witches"],
  ["It is a truth universally acknowledged, that a single man in possession of a good fortune, must be in want of a wife.", "Jane Austen, Pride and Prejudice"],
  ["Call me Ishmael.", "Herman Melville, Moby-Dick"],
  ["Happy families are all alike; every unhappy family is unhappy in its own way.", "Leo Tolstoy, Anna Karenina"],
  ["Life is to be lived, not controlled; and humanity is won by continuing to play in face of certain defeat.", "Ralph Ellison, Invisible Man"],
  ["I will pioneer a new way, explore unknown powers, and unfold to the world the deepest mysteries of creation.", "Mary Shelley, Frankenstein"],
  ["There is a time for many words, and there is also a time for sleep.", "Homer, The Odyssey"],
];
const modern = [
  ["The truest tales require time and familiarity to become what they are.", "Erin Morgenstern, The Night Circus"],
  ["And, when you want something, all the universe conspires in helping you to achieve it.", "Paulo Coelho, The Alchemist"],
  ["I have hated words and I have loved them, and I hope I have made them right.", "Markus Zusak, The Book Thief"],
  ["For you, a thousand times over.", "Khaled Hosseini, The Kite Runner"],
  ["Some infinities are bigger than other infinities.", "John Green, The Fault in Our Stars"],
  ["My life amounts to no more than one drop in a limitless ocean. Yet what is any ocean, but a multitude of drops?", "David Mitchell, Cloud Atlas"],
  ["Books are mirrors: you only see in them what you already have inside you.", "Carlos Ruiz Zafón, The Shadow of the Wind"],
  ["It does not do to dwell on dreams and forget to live.", "J.K. Rowling, Harry Potter and the Philosopher's Stone"],
  ["It matters not what someone is born, but what they grow to be.", "J.K. Rowling, Harry Potter and the Goblet of Fire"],
  ["It is our choices, far more than our abilities, that show what we truly are.", "J.K. Rowling, Harry Potter and the Chamber of Secrets"],
  ["Fear is the mind-killer.", "Frank Herbert, Dune"],
  ["Violence is the last refuge of the incompetent.", "Isaac Asimov, Foundation"],
  ["Don't Panic.", "Douglas Adams, The Hitchhiker's Guide to the Galaxy"],
  ["Go then, there are other worlds than these.", "Stephen King, The Dark Tower"],
  ["Life is difficult.", "M. Scott Peck, The Road Less Traveled"],
];
const ideas = [
  ["The more we understand particular things, the more we understand God.", "Baruch Spinoza, Ethics"],
  ["Knowing others is intelligence; knowing yourself is true wisdom.", "Lao Tzu, Tao Te Ching"],
  ["One must still have chaos in oneself to be able to give birth to a dancing star.", "Friedrich Nietzsche, Thus Spoke Zarathustra"],
  ["Begin with the end in mind.", "Stephen R. Covey, The 7 Habits of Highly Effective People"],
  ["The only way to get the best of an argument is to avoid it.", "Dale Carnegie, How to Win Friends and Influence People"],
  ["Whatever the mind can conceive and believe, it can achieve.", "Napoleon Hill, Think and Grow Rich"],
  ["Change your thoughts and you change your world.", "Norman Vincent Peale, The Power of Positive Thinking"],
  ["Realize deeply that the present moment is all you have.", "Eckhart Tolle, The Power of Now"],
  ["Vulnerability is the birthplace of innovation, creativity, and change.", "Brené Brown, Daring Greatly"],
  ["Success is the product of daily habits, not once-in-a-lifetime transformations.", "James Clear, Atomic Habits"],
  ["When we are no longer able to change a situation, we are challenged to change ourselves.", "Viktor E. Frankl, Man's Search for Meaning"],
];
const bible = [
  ["\"For I know the plans I have for you,\" declares the Lord, \"plans to prosper you and not to harm you, plans to give you hope and a future.\"", "Jeremiah 29:11"],
  ["With God all things are possible.", "Matthew 19:26"],
  ["Do not let your hearts be troubled. Trust in God; trust also in me.", "John 14:1"],
  ["God is our refuge and strength, an ever-present help in trouble.", "Psalm 46:1"],
  ["And now these three remain: faith, hope and love. But the greatest of these is love.", "1 Corinthians 13:13"],
  ["For we walk by faith, not by sight.", "2 Corinthians 5:7"],
  ["Love is patient, love is kind. It does not envy, it does not boast, it is not proud.", "1 Corinthians 13:4"],
  ["I can do all things through Christ who strengthens me.", "Philippians 4:13"],
  ["Trust in the Lord with all your heart and lean not on your own understanding.", "Proverbs 3:5"],
  ["Take delight in the Lord, and he will give you the desires of your heart.", "Psalm 37:4"],
  ["The Lord will fight for you; you need only to be still.", "Exodus 14:14"],
  ["He has made everything beautiful in its time.", "Ecclesiastes 3:11"],
  ["For as he thinks in his heart, so is he.", "Proverbs 23:7"],
  ["Do everything in love.", "1 Corinthians 16:14"],
  ["But I say to you, love your enemies, bless those who curse you, do good to those who hate you, and pray for those who spitefully use you and persecute you.", "Matthew 5:44"],
  ["Let the little children come to me, and do not hinder them, for to such belongs the kingdom of heaven.", "Matthew 19:14"],
  ["No weapon formed against you shall prosper.", "Isaiah 54:17"],
  ["Be strong and courageous. Do not be afraid; do not be discouraged, for the Lord your God will be with you wherever you go.", "Joshua 1:9"],
  ["Come to me, all you who are weary and burdened, and I will give you rest.", "Matthew 11:28"],
  ["The Lord is my shepherd; I shall not want.", "Psalm 23:1"],
  ["Though I walk through the valley of the shadow of death, I will fear no evil, for you are with me.", "Psalm 23:4"],
  ["In truth I perceive that God shows no partiality. But in every nation whoever fears Him and works righteousness is accepted by Him.", "Acts 10:34-35"],
  ["Do not fear or be in dread of them, for it is the Lord your God who goes with you. He will not leave you or forsake you.", "Deuteronomy 31:6"],
  ["Cast all your anxiety on him because he cares for you.", "1 Peter 5:7"],
  ["If God is for us, who can be against us?", "Romans 8:31"],
  ["We know that in all things God works for the good of those who love him.", "Romans 8:28"],
  ["Be still, and know that I am God.", "Psalm 46:10"],
];
const church = [
  ["You have made us for yourself, O Lord, and our hearts are restless until they rest in you.", "Augustine, Confessions"],
  ["Faith is to believe what you do not see; the reward of this faith is to see what you believe.", "Augustine, Sermons"],
  ["The Son of God became a man to enable men to become the sons of God.", "C.S. Lewis, Mere Christianity"],
  ["If I find in myself a desire which no experience in this world can satisfy, the most probable explanation is that I was made for another world.", "C.S. Lewis, Mere Christianity"],
  ["Joy is the serious business of heaven.", "C.S. Lewis, Letters to Malcolm"],
  ["God cannot give us a happiness and peace apart from Himself, because it is not there. There is no such thing.", "C.S. Lewis, Mere Christianity"],
  ["To be a Christian means to forgive the inexcusable because God has forgiven the inexcusable in you.", "C.S. Lewis, The Weight of Glory"],
  ["Faith is the art of holding on to things your reason has once accepted in spite of your changing moods.", "C.S. Lewis, Mere Christianity"],
  ["Love is something more stern and splendid than mere kindness.", "C.S. Lewis, The Problem of Pain"],
  ["The Christian does not think God will love us because we are good, but that God will make us good because He loves us.", "C.S. Lewis, Mere Christianity"],
  ["Pain is God's megaphone to rouse a deaf world.", "C.S. Lewis, The Problem of Pain"],
];
const mix = (...g) => { const out = []; for (let i = 0; g.some(x => i < x.length); i++) g.forEach(x => { if (i < x.length) out.push(x[i]); }); return out; };
export const QUOTES = mix(tolkien, narnia, lit, modern, ideas, bible, church);
